### ISSUE TITLE
Libs roadmap

### ISSUE THREAD

**Issue by assambar** [vmware-labs/webassembly-language-runtimes#78]
### Is your feature request related to a problem? Please describe.

Raw list of things we want to do about the published reusable common libs (not in order):

- [ ] Polish and integrate the intermal wasmedge_sock library into php-8.2.0
- [ ] Writeup a wlr_context library that extracts the common asyncify-based setjmp/longjmp code used by Ruby.
- [ ] Use wlr_context in php-8.2.0
- [ ] Find a curated list of next libraries to patch
- [ ] Add an autoconf based example in libs/examples (we only got a CMake based one now)

### Describe the solution you'd like

.
